# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import induced_ai_python_sdk
from induced_ai_python_sdk.paths.autonomous import post
from induced_ai_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestAutonomous(ApiTestMixin, unittest.TestCase):
    """
    Autonomous unit test stubs
        Execute an Autonomous Task
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
