# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import induced_ai_python_sdk
from induced_ai_python_sdk.model.extraction_from_url_request import ExtractionFromUrlRequest
from induced_ai_python_sdk import configuration


class TestExtractionFromUrlRequest(unittest.TestCase):
    """ExtractionFromUrlRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
