# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import induced_ai_python_sdk
from induced_ai_python_sdk.model.task_execute_request import TaskExecuteRequest
from induced_ai_python_sdk import configuration


class TestTaskExecuteRequest(unittest.TestCase):
    """TaskExecuteRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
