# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import induced_ai_python_sdk
from induced_ai_python_sdk.model.feedback_submission_request import FeedbackSubmissionRequest
from induced_ai_python_sdk import configuration


class TestFeedbackSubmissionRequest(unittest.TestCase):
    """FeedbackSubmissionRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
