# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ExtractionFromUrlRequest(BaseModel):
    url: typing.Optional[str] = Field(None, alias='url')

    query: typing.Optional[str] = Field(None, alias='query')

    columns: typing.Optional[str] = Field(None, alias='columns')

    limit: typing.Optional[int] = Field(None, alias='limit')

    format: typing.Optional[Literal["json", "csv", "markdown"]] = Field(None, alias='format')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
