# coding: utf-8

# flake8: noqa

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from induced_ai_python_sdk.api_client import ApiClient

# import Configuration
from induced_ai_python_sdk.configuration import Configuration

# import exceptions
from induced_ai_python_sdk.exceptions import OpenApiException
from induced_ai_python_sdk.exceptions import ApiAttributeError
from induced_ai_python_sdk.exceptions import ApiTypeError
from induced_ai_python_sdk.exceptions import ApiValueError
from induced_ai_python_sdk.exceptions import ApiKeyError
from induced_ai_python_sdk.exceptions import ApiException

from induced_ai_python_sdk.client import InducedAi
