# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from induced_ai_python_sdk.paths.autonomous_id.get import GetResult
from induced_ai_python_sdk.paths.autonomous_id_stop.post import TerminateTask
from induced_ai_python_sdk.apis.tags.autonomous_api_raw import AutonomousApiRaw


class AutonomousApi(
    GetResult,
    TerminateTask,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AutonomousApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AutonomousApiRaw(api_client)
