# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from induced_ai_python_sdk.paths.extract.post import FromUrlRaw
from induced_ai_python_sdk.paths.extract_id.get import GetResultRaw


class ExtractionApiRaw(
    FromUrlRaw,
    GetResultRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
