# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from induced_ai_python_sdk.paths.autonomous_id_feedback.post import Submission
from induced_ai_python_sdk.apis.tags.feedback_api_raw import FeedbackApiRaw


class FeedbackApi(
    Submission,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FeedbackApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FeedbackApiRaw(api_client)
