# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from induced_ai_python_sdk.paths.autonomous.post import Execute
from induced_ai_python_sdk.apis.tags.task_api_raw import TaskApiRaw


class TaskApi(
    Execute,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TaskApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TaskApiRaw(api_client)
