# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExtractionFromUrlRequest(TypedDict):
    pass

class OptionalExtractionFromUrlRequest(TypedDict, total=False):
    url: str

    query: str

    columns: str

    limit: int

    format: str

class ExtractionFromUrlRequest(RequiredExtractionFromUrlRequest, OptionalExtractionFromUrlRequest):
    pass
