# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from induced_ai_python_sdk.type.extraction_from_url_response_data import ExtractionFromUrlResponseData

class RequiredExtractionFromUrlResponse(TypedDict):
    pass

class OptionalExtractionFromUrlResponse(TypedDict, total=False):
    success: bool

    data: ExtractionFromUrlResponseData

    requestId: str

    timeTaken: int

class ExtractionFromUrlResponse(RequiredExtractionFromUrlResponse, OptionalExtractionFromUrlResponse):
    pass
