# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExtractionFromUrlResponseData(TypedDict):
    pass

class OptionalExtractionFromUrlResponseData(TypedDict, total=False):
    id: str

    status: str

    objective: str

class ExtractionFromUrlResponseData(RequiredExtractionFromUrlResponseData, OptionalExtractionFromUrlResponseData):
    pass
