# coding: utf-8

"""
    Autonomous API

    Building the next evolution of actionable AI.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from induced_ai_python_sdk.type.task_execute_response_data import TaskExecuteResponseData

class RequiredTaskExecuteResponse(TypedDict):
    pass

class OptionalTaskExecuteResponse(TypedDict, total=False):
    success: bool

    data: TaskExecuteResponseData

    requestId: str

    timeTaken: int

class TaskExecuteResponse(RequiredTaskExecuteResponse, OptionalTaskExecuteResponse):
    pass
